### ISSUE TITLE
virtual participation?

### ISSUE THREAD

**Issue by BrianStucky-USDA** [autogluon/neurips-autogluon-workshop#6]
Hello,
Thanks so much for organizing this workshop!  Is there any chance there will be a way for virtual NeurIPS attendees to participate?  I would very much like to join, if possible.
Thank you!

**Comment by BrianStucky-USDA** [comment]
To update my question above, were the workshop presentations recorded by any chance? It would be great if virtual NeurIPS participants could have a way to view them.

**Comment by Innixma** [comment]
The workshop was not recorded in 2022, sorry. Good news though: Our 2024 presentation will be recorded!
